In [1]:
from dotenv import load_dotenv
import os
from pathlib import Path
load_dotenv()
PATH_FINTOC_2022 = Path(os.getenv('PATH_FINTOC_2022'))

In [2]:
FINTOC_EN = PATH_FINTOC_2022/'data'/'en'
FINTOC_EN_PDF =FINTOC_EN/'pdf'
FINTOC_EN_ANNOTS = FINTOC_EN/'annots'
FINTOC_EN_PRED = FINTOC_EN/'preds'

JSON_EXTENSION = "fintoc4.json"

In [3]:
if not FINTOC_EN_PRED.exists():
    FINTOC_EN_PRED.mkdir()
FILE_PATHS = list(FINTOC_EN_PDF.iterdir())
FILE_PATHS.sort()
FILE_PATHS = FILE_PATHS[:10]

In [4]:
import json

import pager
from pager.pager_pipe_line import pdf2region_row

from pager.doc_model import MinerPDFModel
from pager.doc_model import LogicTreeModel
from pager.doc_model.converters import PDF2LogicTree
from pager.doc_model.dtype import Document, Page
from pager import Region

from typing import Dict

pdf_reader = MinerPDFModel({"page_model": pdf2region_row})
pdf2tree = PDF2LogicTree()
tree = LogicTreeModel()

In [5]:
file_path = FILE_PATHS[0]
pdf_reader.read_from_file(file_path)
pdf_reader.extract()
pdf2tree.convert(pdf_reader, tree)
file_path

/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch_geometric/nn/conv/tag_conv.py:102: UserWarning: Converting sparse tensor to CSR format for more efficient processing. Consider converting your sparse tensor to CSR format beforehand to avoid repeated conversion (got 'torch.sparse_coo')
  return spmm(adj_t, x, reduce=self.aggr)
/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch_geometric/utils/_spmm.py:71: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  src = src.to_sparse_csr()
/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch/nn/modules/module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)

PosixPath('/home/dataset/fintoc2022/data/en/pdf/1.9.900555.pdf')

# Отладка на одном документе

In [6]:
doc_regions = [region for page in tree.document.pages for region in page.regions]
regions_num_page = [page.num_page for page in tree.document.pages for _ in page.regions]

In [7]:
# for region in doc_regions:
#     print(region.md)

### Кластер регионов

In [9]:
_font_from_doc = {}
_list_font_type = []
def get_vec_feature(row):
    fd = row.font.to_dict()
    name = fd['name']
    size = int(round(fd['size']/2))
    width = int(round(fd['width']/0.1))
    italic = int(round(fd['italic']/0.1))
    return (name, size, width, italic)

def get_id_exist_cluster(feature):
    _list_font_type.append(feature)
    if feature in _font_from_doc.keys():
         return _font_from_doc[feature] 
    return None
        
def add_new_cluster(feature):
    indexs= list(_font_from_doc.values())
    index = max(indexs)+1 if len(indexs) != 0 else 0
    _font_from_doc[feature] = index
    clusters[index] = []
    return index
    
clusters = {}
for region in doc_regions:
    feature_row = get_vec_feature(region)
    index = get_id_exist_cluster(feature_row)
    if index is None:
        index = add_new_cluster(feature_row)
    clusters[index].append(region)

### Поиск кластера основного текста

In [10]:
max_clust = -1
max_size = 0
for ind, regions in clusters.items():
    count_word = len([w for reg in regions for w in reg.words])
    if max_size < count_word:
        max_clust = ind
        max_size = count_word
font_text =  clusters[max_clust][0].rows[0].font
print(max_size)
font_text.to_dict()

5392

{'name': 'EPEAMU+NotoSans',
 'width': 0.0,
 'italic': 0.0,
 'size': 8.499899999999911}

### Поиск кластеров заголовков

In [11]:
header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > font_text}

### Сортировка кластеров заголовков

In [12]:
header_cluster_index = list(header_cluster.keys())
header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)
for header_ind in header_cluster_index:
    print(get_vec_feature(header_cluster[header_ind]))

level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
# level_header_cluster

('TKRTDS+SchrodersCircular-Bold', 14, 10, 0)
('TKRTDS+SchrodersCircular-Bold', 11, 10, 0)
('TKRTDS+SchrodersCircular-Bold', 12, 10, 0)
('EPEAMU+NotoSans', 12, 2, 0)
('EPEAMU+NotoSans', 12, 0, 0)
('EPEAMU+NotoSans', 8, 0, 0)
('TKRTDS+SchrodersCircular-Bold', 6, 10, 0)
('QHVYUR+NotoSans-Bold', 6, 10, 0)
('EPEAMU+NotoSans', 6, 5, 0)
('EPEAMU+NotoSans', 6, 3, 0)
('EPEAMU+NotoSans', 6, 1, 0)
('XFMZLQ+SchrodersCircular-Book', 6, 0, 0)
('TKRTDS+SchrodersCircular-Bold', 5, 10, 0)
('QHVYUR+NotoSans-Bold', 5, 10, 0)
('XFMZLQ+SchrodersCircular-Book', 8, 0, 0)
('EPEAMU+NotoSans', 5, 2, 0)
('EPEAMU+NotoSans', 5, 1, 0)
('EPEAMU+NotoSans', 5, 5, 0)
('TKRTDS+SchrodersCircular-Bold', 5, 7, 0)
('EPEAMU+NotoSans', 5, 0, 0)
('EPEAMU+NotoSans', 6, 0, 0)
('EPEAMU+NotoSans', 6, 2, 0)
('QHVYUR+NotoSans-Bold', 4, 10, 0)
('TKRTDS+SchrodersCircular-Bold', 4, 10, 0)

### Создание регионов

In [13]:
num_cluster = [ _font_from_doc[vec] for vec in _list_font_type]

def seg_region(region, cl, num_page):
    
    if cl in level_header_cluster:
        region.header_level = level_header_cluster[cl]
        region.label = 'header'
    else:
        region.label = 'other'
    return region

page_regions = dict()
for region, cl, num_page in zip(doc_regions, num_cluster, regions_num_page):
    seg_region(region, cl, num_page)
    if num_page in page_regions:
        page_regions[num_page].append(region)
    else:
        page_regions[num_page] = [region]

### Построение дерева (Переиспользование класса конвертера)

In [14]:


class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, regions, output_model:LogicTreeModel):
        reg_pages = [(n, reg) for n, reg in  page_regions.items()]
        reg_pages.sort(key= lambda x: x[0])
        document = Document([Page(regions=regs, num_page=num) for num, regs in (reg_pages)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree


creater = CustomJson2LogicTree()
tree = LogicTreeModel()
creater.upload(regions, tree)

In [15]:
print(tree.document.md)

# (a Luxembourg domiciled open-ended investment company)

# Schroder GAIA

# Prospectus

## August 2019

# United Kingdom


<!-- page_num: 0 -->
---Schroder GAIA

(a Luxembourg domiciled open-ended investment company)

# Prospectus

## August 2019

Schroder Investment Management (Europe) S.A.

Internet Site: www.schroders.lu


<!-- page_num: 2 -->
---## Important Information

Copies of this Prospectus can be obtained from and enquiries regarding the Company should be addressed to:

Schroder Investment Management (Europe) S.A. 5, rue Höhenhof 1736 Senningerberg Grand Duchy of Luxembourg Tel: (+352) 341 342 202 Fax: (+352) 341 342 342

This prospectus (the "Prospectus") should be read in its

entirety before making any application for Shares. If you are in any doubt about the contents of this Prospectus you should consult your financial or other professional adviser. Shares are offered on the basis of the information contained

in this Prospectus and the documents referred to herein. No person has been authorised to issue any advertisement or to give any information, or to make any representations in connection with the offering, placing, subscription, sale, switching or redemption of Shares other than those contained in this Prospectus and, if issued, given or made, such advertisement, information or representations must not be relied upon as having been authorised by the Company or the Management Company. Neither the delivery of this Prospectus nor the offer, placement, subscription or issue of any of the Shares shall under any circumstances create any implication or constitute a representation that the information given in this Prospectus is correct as of any time subsequent to the date hereof. The Directors, whose names appear below, have taken all reasonable care to ensure that the information contained in this Prospectus is, to the best of their knowledge and belief, in accordance with the facts and does not omit anything material to such information. The Directors accept responsibility accordingly. The distribution of this Prospectus and supplementary documentation and the offering of Shares may be restricted in certain countries. Investors wishing to apply for Shares should inform themselves as to the requirements within their own country for transactions in Shares, any applicable exchange control regulations and the tax consequences of any transaction in Shares. This Prospectus does not constitute an offer or solicitation by anyone in any country in which such offer or solicitation is not lawful or authorised, or to any person to whom it is unlawful to make such offer or solicitation. Investors should note that not all of the protections provided under their relevant regulatory regime may apply and there may be no right to compensation under such regulatory regime, if such scheme exists. For the purposes of the General Data Protection Regulation 2016/679 (“GDPR”), the data controller in relation to any

personal data you supply are the Company and the

Management Company.

In order to comply with the obligations and responsibilities under the GDPR, the Company and the Management Company are required by law to make available to you a privacy policy which details how Schroders collect, use, disclose, transfer, and store your information. Please find a

copy of the privacy policy at www.schroders.com/en/privacy- policy. You hereby acknowledge that you have read and understood the contents of the privacy policy.

The distribution of this Prospectus in certain countries may require that this Prospectus be translated into the languages specified by the regulatory authorities of those countries. Should any inconsistency arise between the translated and the English version of this Prospectus, the English version

shall always prevail. The Management Company may use telephone recording procedures to record any conversation. Investors are deemed to consent to the recording of conversations with the Management Company and to the use of such recordings by the Management Company and/or the Company in legal proceedings or otherwise at their discretion.

### The price of Shares in the Company and the income from them may go down as well as up and an Investor may not

### get back the amount invested.

Schroder GAIA Prospectus

#### 5


<!-- page_num: 4 -->
---## Table of Contents

### Important Information . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

### 5

#### Definitions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7 10 Directors . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11 Administration . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Section 1 1. The Company . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1.1. Structure 12 12 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1.2. Investment Objectives and Policies 1.3. Share Classes . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12 2. Share Dealing . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16 Section 2 2.1. Subscription for Shares 16 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.2. Redemption and Switching of Shares 18 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.3. Restrictions on Subscriptions and Switches into certain Funds or Classes 20 2.4. Calculation of Net Asset Value . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20 2.5. Suspensions or Deferrals 22 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2.6. Market Timing and Frequent Trading Policy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22 3. General Information . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 24 Section 3 24 3.1. Administration Details, Charges and Expenses . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3.2. Performance Fees 28 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 29 3.3. Company Information . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3.4. Dividends . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30 3.5. Taxation 32 3.6. Meetings and Reports . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 33 3.7. Details of Shares . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 33 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3.8. Information Addressed To UK Investors 35 Investment Restrictions . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Appendix I 42 Appendix II Risks of Investment . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Appendix III 53 Fund Details . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 55 Category 1 – Externally Managed Funds . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Schroder GAIA BlueTrend . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 55 58 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Schroder GAIA Contour Tech Equity Schroder GAIA Egerton Equity . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 60 Schroder GAIA Nuveen US Equity Long Short* . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 62 64 Schroder GAIA Nuveen US Equity Market Neutral* . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 66 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Schroder GAIA Sirios US Equity Schroder GAIA UK Dynamic Absolute Return Fund . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 68 Schroder GAIA Two Sigma Diversified . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 70 Schroder GAIA Wellington Pagosa . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 72 75 Category 2 – Internally Managed Funds . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Schroder GAIA Cat Bond 75 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Schroder GAIA Helix . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 78 81 Other information . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Appendix IV

##### 6

Schroder GAIA Prospectus


<!-- page_num: 5 -->
---## Definitions

### Accumulation Shares or ACC Shares

shares which accumulate their income so that the income is included in the price of the shares

### Administration Agent

Brown Brothers Harriman (Luxembourg) S.C.A.

### Articles

the Articles of Association of the Company as amended from time to time

### Benchmark

such benchmark (if any) identified in the Performance Fee section of the table entitled "Fund Characteristics" for the relevant Fund set out in Appendix III

### Business Day

a week day other than New Year's Day, Good Friday, Easter Monday, Christmas Eve, Christmas Day and the day following Christmas Day, unless otherwise provided in the Fund’s details in Appendix III.

### Calculation Day

a Business Day on which the Net Asset Value per Share is calculated for a Share Class and/or a Fund, as defined for each Fund in Appendix III. The Management Company may also take into account whether relevant local stock exchanges and/or Regulated Markets are open for trading and settlement, and may elect to treat such closures as non- Calculation Days for Funds which invest a substantial amount of their portfolio on these closed stock exchanges and/or

Regulated Markets

### China A-Shares

equity securities of Chinese companies listed and traded in RMB on Chinese stock exchanges such as Shenzhen or

Shanghai Stock Exchanges

### China B-Shares

equity securities of Chinese companies listed and traded in HKD or USD on Chinese stock exchanges such as Shenzhen or Shanghai Stock Exchanges

### China H-Shares

equity securities of Chinese companies listed and traded in Hong Kong Stock Exchange or other foreign exchanges

### Company

Schroder GAIA

### Credit

Sub-Funds following a credit strategy seek to isolate one or

all the specific risks related to credit instruments. The traditional credit risks being traded are: the default risk, the credit spread risk and the illiquidity risk. Sub-Funds following

this strategy typically take long and short positions in fixed and floating rate securities. They may gain this exposure directly and/or indirectly through derivatives.

### CSSF

Commission de Surveillance du Secteur Financier (Luxembourg Financial Sector Supervisory Authority)

### Dealing Cut-off Time

the time by which dealing instructions must be received by the Management Company in order to be executed on a Dealing Day as defined for each Fund in Appendix III

### Dealing Day

a Business Day on which dealing instructions received for a Fund are executed, as defined for each Fund in Appendix III. A Business Day on which dealing instructions for a Fund are executed, shall not fall within a period of suspension of calculation of the Net Asset Value per Share of the relevant Share Class or of the Net Asset Value of the relevant Fund. The Management Company may also take into account whether relevant local stock exchanges and/or Regulated Markets on which any substantial portion of the Company’s investments of the relevant Fund are quoted are closed for trading and settlement, and whether underlying Investment Funds representing a material part of the assets the relevant

Fund invests in are closed for dealing and/or the determination of the Net Asset Value per Share is suspended. The Management Company may elect to treat such closures as non-Dealing Days for Funds which invest a substantial amount of their portfolio on these closed stock exchanges and/or Regulated Markets and/or these closed underlying Investment Funds. A list of expected non-Dealing Days for the Funds is available from the Management Company on request and is also available on the Internet site www.schroders.lu

### Depositary

#### Brown Brothers Harriman (Luxembourg) S.C.A. Directors or Board of Directors

the board of directors of the Company

### Distributor

a person or entity duly appointed from time to time by the Management Company to distribute or arrange for the

distribution of Shares

### Distribution Shares

shares which distribute their income

### EEA

European Economic Area

Schroder GAIA Prospectus

#### 7


<!-- page_num: 6 -->
---### Eligible State

includes any member state of the European Union, any member state of the Organisation for Economic Co-operation and Development ("OECD"), and any other state which the

Directors deem appropriate

### Event Driven

Sub-Funds following this strategy attempt to profit from prices changes or mispricing of securities in anticipation of or

in response to certain corporate actions, such as

bankruptcies, mergers and acquisitions, restructuring, take overs, emergence from bankruptcy, shifts in corporate strategy, and other atypical events.

### Exchange Traded Fund or ETF

an investment fund listed on a stock exchange which represents a pool of securities, commodities or currencies which typically track the performance of an index. Exchange Traded Funds (ETFs) are traded like shares. Investment in open-ended or closed-ended ETFs will be allowed if they qualify as (i) UCITS or other UCIs or (ii) transferable

securities, respectively.

### EU

European Union

### EUR

the European currency unit (also referred to as the Euro)

### Financial Year

means a period of 12 months ending on 30 September

### Fund

a specific portfolio of assets and liabilities within the Company, being a sub-fund of the Company and having its own Net Asset Value and represented by a separate Share

Class or Share Classes

### GAIA

Global Alternative Investor Access

### GBP

Great British Pound

### Global Macro

Sub-Funds following this strategy make investment decisions

based on an assessment of the broad macro-economic

environment. These Sub-Funds are not restricted by asset class and may invest in assets such as equities, bonds,

currencies, derivatives, and commodities. Typically, these

funds invest indirectly through derivatives.

### High Water Mark

has the meaning given to it in section 3.2(A)(1)

#### 8

Schroder GAIA Prospectus

### Hurdle

such hurdle (if any) identified in the Performance Fee section of the table entitled "Fund Characteristics" for the relevant Fund set out in Appendix III

### Investment Adviser

Schroder Investment Management Limited

### Investment Fund(s)

a UCITS or other UCI in which the Funds may invest, as determined in the investment rules described in Appendix I

#### Investment Manager any investment manager appointed by the Management Company, to manage each Fund under its supervision

### Investor

a subscriber for Shares

### Law

the law on undertakings for collective investment dated 17 December 2010, as may be amended from time to time

### Long/Short equity

Sub-Funds following this strategy typically take long and short positions in equity and equity related securities where an increase, or respectively a decrease of the value of such position is expected. They may gain this exposure directly and/or indirectly through derivatives.

### Management Company

Schroder Investment Management (Europe) S.A.

### Market Neutral

Sub-Funds following this strategy attempt to reduce systematic risk created by factors such as exposures to sectors, market-cap ranges, investment styles, currencies, and/or countries, by matching short positions against long positions within each area.

### Net Asset Value

the assets less the liabilities of the relevant Fund or Share Class as reflected in the most recent calculations which shall be carried out in a manner consistent with the basis for calculating the Net Asset Value in the latest annual or semi-

annual financial report of the relevant Fund

#### Net Asset Value per Share the Net Asset Value of the relevant Share Class divided by the number of Shares of the relevant Share Class then in issue

### OTC

over-the-counter

### Performance Period

has the meaning given to it in section 3.2(A)


<!-- page_num: 7 -->
---### Real Estate Investment Fund or REIT

is an entity that is dedicated to owning, and in most cases, managing real estate. This may include, but is not limited to, real estate in the residential (apartments), commercial (shopping centres, offices) and industrial (factories,

warehouses) sectors. Certain REITs may also engage in real estate financing transactions and other real estate

development activities. The legal structure of a REIT, its investment restrictions and the regulatory and taxation regimes to which it is subject will differ depending on the

jurisdiction in which it is established. Investment in REITs will be allowed if they qualify as (i) UCITS or other UCIs or (ii) transferable securities. A closed-ended REIT, the units of which are listed on a Regulated Market is classified as a transferable security listed on a Regulated Market thereby qualifying as an eligible investment for a UCITS under the

Luxembourg Law

### Reference Currency

the currency in which a Share Class is offered to Investors

### Regulated Market

a market within the meaning of Directive 2004/39/EC of the European Parliament and of the Council of 21 April 2004 on

markets in financial instruments or another regulated market which operates regularly and is recognised and open to the public in an Eligible State

### Regulations

Part I of the Law as well as any present or future related

Luxembourg laws or implementing regulations, circulars and

CSSF’s positions applicable to UCITS

### Relative Value

Sub-Funds following this strategy seek to take advantage of

price differentials between related financial instruments, by simultaneously buying and selling the different securities with a view to making a profit from the “relative value” of the two securities.

### Reporting Fund

a Fund or a Share Class that complies with UK HMRC’s tax regime for offshore funds and therefore has a certain tax status relevant for UK tax paying Shareholders

### Research Payment Account or RPA

in relation to a Fund, is an account established for the

provision of research by third parties to the relevant Sub- Investment Manager and funded by such Fund in accordance with in Article 13 of the Commission Delegated Directive (EU) 2017/593 of 7 April 2016 supplementing Directive 2014/65/EU

### Schroders

Schroders plc., the Management Company’s and Investment Adviser’s ultimate holding company, and its subsidiaries and

affiliates worldwide

### Share

a share of no par value in any one Share Class in the capital of the Company

### Share Class


# Упаковка в один класс

In [8]:
class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, reg_page, output_model:LogicTreeModel):
        reg_page = [(n, reg) for n, reg in  reg_page.items()]
        reg_page.sort(key= lambda x: x[0])
        reg_page = [regs for n, regs in reg_page]
        document = Document([Page(regions=regs, num_page=num) for num, regs in enumerate(reg_page)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree

class ExtractTree:
    def __init__(self):
        self.creater = CustomJson2LogicTree()
        self._font_from_doc = {}
        self._list_font_type = []

        
    def extract(self, tree:LogicTreeModel):
        doc_regions = [region for page in tree.document.pages for region in page.regions]
        region_num_page = [page.num_page for page in tree.document.pages for _ in page.regions]
        clusters = self.get_cluster(doc_regions)
        level_header_cluster = self.get_level_header(clusters)
        page_regions = self.get_regions(doc_regions, region_num_page, level_header_cluster)
        self.creater.upload(page_regions, tree)


    def get_regions(self, doc_regions, regions_num_page, level_header_cluster):
        num_cluster = [self._font_from_doc[vec] for vec in self._list_font_type]

        def seg_region(region, cl, num_page):
            
            if cl in level_header_cluster:
                region.header_level = level_header_cluster[cl]
                region.label = 'header'
            else:
                region.label = 'other'
            return region
        
        page_regions = dict()
        for region, cl, num_page in zip(doc_regions, num_cluster, regions_num_page):
            seg_region(region, cl, num_page)
            if num_page in page_regions:
                page_regions[num_page].append(region)
            else:
                page_regions[num_page] = [region]

        return page_regions

        
    def get_level_header(self, clusters):
        main_clust, main_font = self.get_main_cluster(clusters)
        header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > main_font}
        header_cluster_index = list(header_cluster.keys())
        header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)        
        level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
        return level_header_cluster
        
    def get_main_cluster(self, clusters):
        def get_words(reg):
            words = []
            for row in reg.rows:
                words.extend(row.words)
            return words
        max_clust = -1
        max_size = 0
        for ind, regions in clusters.items():
            
            count_word = len([w for reg in regions for w in get_words(reg)])
            if max_size < count_word:
                max_clust = ind
                max_size = count_word
        font_text =  clusters[max_clust][0].rows[0].font
        return max_clust, font_text

    def get_cluster(self, doc_regions):
        self._font_from_doc = {}
        self._list_font_type = []
        def get_vec_feature(row):
            fd = row.font.to_dict()
            name = fd['name']
            size = int(round(fd['size']/2))
            width = int(round(fd['width']/0.1))
            italic = int(round(fd['italic']/0.1))
            return (name, size, width, italic)
        
        def get_id_exist_cluster(feature):
            self._list_font_type.append(feature)
            if feature in self._font_from_doc.keys():
                 return self._font_from_doc[feature] 
            return None
                
        def add_new_cluster(feature):
            indexs= list(self._font_from_doc.values())
            index = max(indexs)+1 if len(indexs) != 0 else 0
            self._font_from_doc[feature] = index
            clusters[index] = []
            return index
            
        clusters = {}
        for region in doc_regions:
            feature_row = get_vec_feature(region)
            index = get_id_exist_cluster(feature_row)
            if index is None:
                index = add_new_cluster(feature_row)
            clusters[index].append(region)
        return clusters
        
       
     
   

extract_tree=ExtractTree()

In [9]:
def tree2fintoc_json(doc_tree) -> Dict:
    fintoc_json = []
    for id_node, node in doc_tree['nodes']['regions'].items():
        if node['label'] == 'header':
            reg = {
                "text":node['text'],
                "id": id_node,
                "page": node['metainfo']['page'] + 1, # В PageR специально оставил нумерацию с нуля (поскольку номер определяется не порядком, а пишится на странице и это еще не реализовано)
                "depth": node['header_level']
            }
            fintoc_json.append(reg)
    return fintoc_json

N = len(FILE_PATHS)
for i, file_path in enumerate(FILE_PATHS):    
    pdf_reader.read_from_file(file_path)
    pdf_reader.extract()
    pdf2tree.convert(pdf_reader, tree)
    extract_tree.extract(tree)
    
    doc_tree = tree.to_dict()
    pred_path = FINTOC_EN_PRED/(file_path.name+'.'+JSON_EXTENSION)
    # print(tree.document.md)
    
    rez = tree2fintoc_json(doc_tree)
    with open(pred_path, 'w') as f:
        json.dump(rez, f)

    print(f'{i+1}/{N} ({(i+1)/N*100:.2f}%)')

1/10 (10.00%)
2/10 (20.00%)
3/10 (30.00%)
4/10 (40.00%)
5/10 (50.00%)
6/10 (60.00%)
7/10 (70.00%)
8/10 (80.00%)
9/10 (90.00%)
10/10 (100.00%)

In [10]:
import subprocess
import pandas as pd

In [11]:
subprocess.run(['python', 'metric.py', '--gt_folder', FINTOC_EN_ANNOTS, '--submission_folder', FINTOC_EN_PRED])
df = pd.read_csv('td_report.csv', delimiter='\t')
df[-2:-1][['Prec', 'Rec', 'F1']]

                   Prec                 Rec                  F1
189  0.5559832458911166  0.5127790935638992  0.5190581039800979

In [12]:
df = pd.read_csv('toc_report.csv', delimiter='\t')
tbl = df[-4:-3]
tbl[['Inex08-P', 'Inex08-R', 'Inex08-F1', 'Inex08-Title acc', 'Inex08-Level acc']]

    Inex08-P Inex08-R Inex08-F1 Inex08-Title acc Inex08-Level acc
215     31.1     25.5      27.3             40.3             19.2

In [70]:
df = pd.read_csv('toc_report.csv', delimiter='\t')
tbl = df[-4:-3]
tbl[['Inex08-P', 'Inex08-R', 'Inex08-F1', 'Inex08-Title acc', 'Inex08-Level acc']]

    Inex08-P Inex08-R Inex08-F1 Inex08-Title acc Inex08-Level acc
170     26.8     23.8      24.8             36.6             13.3