In [1]:
from dotenv import load_dotenv
import os
from pathlib import Path
load_dotenv()
PATH_FINTOC_2022 = Path(os.getenv('PATH_FINTOC_2022'))

In [2]:
FINTOC_EN = PATH_FINTOC_2022/'data'/'en'
FINTOC_EN_PDF =FINTOC_EN/'pdf'
FINTOC_EN_ANNOTS = FINTOC_EN/'annots'
FINTOC_EN_PRED = FINTOC_EN/'preds'

JSON_EXTENSION = "fintoc4.json"

In [3]:
if not FINTOC_EN_PRED.exists():
    FINTOC_EN_PRED.mkdir()
FILE_PATHS = list(FINTOC_EN_PDF.iterdir())[:10]

In [4]:
import json

import pager
from pager.pager_pipe_line import pdf2region_row

from pager.doc_model import MinerPDFModel
from pager.doc_model import LogicTreeModel
from pager.doc_model.converters import PDF2LogicTree

from typing import Dict

pdf_reader = MinerPDFModel({"page_model": pdf2region_row})
pdf2tree = PDF2LogicTree()
tree = LogicTreeModel()

/Users/macbookair/program/python/PageR/src/pager/page_model/sub_models/dtype/region.py:114: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if self.label is 'header':

In [5]:
file_path = FILE_PATHS[0]
pdf_reader.read_from_file(file_path)
pdf_reader.extract()
pdf2tree.convert(pdf_reader, tree)
file_path

/Users/macbookair/program/python/PageR/env/lib/python3.13/site-packages/torch_geometric/nn/conv/tag_conv.py:102: UserWarning: Converting sparse tensor to CSR format for more efficient processing. Consider converting your sparse tensor to CSR format beforehand to avoid repeated conversion (got 'torch.sparse_coo')
  return spmm(adj_t, x, reduce=self.aggr)
/Users/macbookair/program/python/PageR/env/lib/python3.13/site-packages/torch_geometric/utils/_spmm.py:71: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:51.)
  src = src.to_sparse_csr()
/Users/macbookair/program/python/PageR/env/lib/python3.13/site-packages/torch/nn/modules/module.py:1776: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)

PosixPath('/Users/macbookair/program/datasets/fintoc2022/data/en/pdf/LU0705072691-LU0705072345-LU0705072188_English_2015_RAM-LUX-Long-Sh-EmergingMarktesEq-.pdf')

# Отладка на одном документе

In [6]:
doc_rows = [row for page in tree.document.pages for row in page.rows]
row_num_page = [page.num_page for page in tree.document.pages for _ in page.rows]

In [9]:
# for row in doc_rows:
#     print(row.text)

### Кластер строк

In [10]:
_font_from_doc = {}
_list_font_type = []
def get_vec_feature(row):
    fd = row.font.to_dict()
    name = fd['name']
    size = int(round(fd['size']/2))
    width = int(round(fd['width']/0.1))
    italic = int(round(fd['italic']/0.1))
    return (name, size, width, italic)

def get_id_exist_cluster(feature):
    _list_font_type.append(feature)
    if feature in _font_from_doc.keys():
         return _font_from_doc[feature] 
    return None
        
def add_new_cluster(feature):
    indexs= list(_font_from_doc.values())
    index = max(indexs)+1 if len(indexs) != 0 else 0
    _font_from_doc[feature] = index
    clusters[index] = []
    return index
    
clusters = {}
for row in doc_rows:
    feature_row = get_vec_feature(row)
    index = get_id_exist_cluster(feature_row)
    if index is None:
        index = add_new_cluster(feature_row)
    clusters[index].append(row)

### Поиск кластера основного текста

In [11]:
max_clust = -1
max_size = 0
for ind, rows in clusters.items():
    if max_size < len(rows):
        max_clust = ind
        max_size = len(rows)
font_text =  clusters[max_clust][0].font
print(max_size)
font_text.to_dict()

5484

{'name': 'Helvetica', 'width': 0.0, 'italic': 0.0, 'size': 9.95999999999998}

### Поиск кластеров заголовков

In [12]:
header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > font_text}

### Сортировка кластеров заголовков

In [13]:
header_cluster_index = list(header_cluster.keys())
header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)
for header_ind in header_cluster_index:
    print(get_vec_feature(header_cluster[header_ind]))

level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
# level_header_cluster

('Helvetica-Bold', 10, 10, 0)
('Helvetica-Bold', 9, 10, 0)
('Helvetica-Bold', 8, 10, 0)
('Helvetica-Bold', 7, 10, 0)
('Helvetica-Bold', 6, 10, 0)
('Helvetica-Bold', 5, 10, 0)
('Arial,Bold', 5, 10, 0)
('Helvetica-Bold', 5, 9, 0)
('Symbol', 6, 9, 0)
('Symbol', 5, 9, 0)
('Helvetica-Bold', 4, 10, 0)
('Helvetica-Bold', 2, 10, 0)
('ABCDEE+Arial Narrow', 6, 0, 0)

### Создание регионов

In [14]:
num_cluster = [ _font_from_doc[vec] for vec in _list_font_type]
regions = []

def get_region(row, cl, num_page):
    tmp_reg = {
        "rows": [row],
        "label": "header" if cl in level_header_cluster else "text",
        "metainfo": {"page": num_page}
    }
    if cl in level_header_cluster:
        tmp_reg["header_level"] = level_header_cluster[cl]
    return tmp_reg

tmp_cl = num_cluster[0]
tmp_num_page = 0
tmp_reg = get_region(rows[0].to_dict(), tmp_cl, tmp_num_page)
for row, cl, num_page in zip(doc_rows[1:], num_cluster[1:], row_num_page[1:]):
    if cl == tmp_cl and num_page==tmp_num_page:
        tmp_reg['rows'].append(row.to_dict())
    else:
        regions.append(tmp_reg.copy())
        tmp_cl = cl
        tmp_num_page = num_page
        tmp_reg = get_region(row.to_dict(), cl,num_page)

### Построение дерева (Переиспользование класса конвертера)

In [15]:
from pager.doc_model import PDF2LogicTree, LogicTreeModel
from pager.doc_model.dtype import Document, Page
from pager import Region

class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, regions, output_model:LogicTreeModel):
        reg_page = [[]]
        tmp_page = 0
        for reg in regions:
            if tmp_page == reg['metainfo']["page"]:
                reg_page[tmp_page].append(reg)
            else:
                reg_page.append([reg])
                tmp_page += 1
            
        document = Document([Page(regions=[Region(r) for r in regs], num_page=num) for num, regs in enumerate(reg_page)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree


creater = CustomJson2LogicTree()
tree = LogicTreeModel()
creater.upload(regions, tree)

In [17]:
print(tree.document.md)

# 4.  In the event that an asset or a liability of the Company cannot be attributed to a given sub-

# Luxembourg SICAV with multiple sub-funds

## PROSPECTUS & ARTICLES OF ASSOCIATION

### JANUARY 2015

Subscriptions may only be carried out on the basis of this prospectus (the “Prospectus”), including

the  articles  of  association  and  the  factsheets  for  each  sub-fund,  and  on  the  basis  of  the  key

investor information document (“KIID”). The Prospectus can only be distributed if accompanied by

the latest annual report or semi-annual report, whichever is the most recent. The  fact  that  the  SICAV  is  registered  on  the  official  list  drawn  up  by  the  Luxembourg  financial

sector  regulator,  the  Commission  de  Surveillance  du  Secteur  Financier  (“CSSF”),  should  not  be

interpreted  under  any  circumstances  or  in  any  way  whatsoever  as  a  positive  assessment  by  the CSSF of the quality of the shares offered for subscription. No  parties  are  authorised  to  provide  information  other  than  that  contained  in  the  Prospectus,  the KIID and these articles of association as well as the documents mentioned herein.


<!-- page_num: 0 -->
---#### RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

##### TABLE OF CONTENTS

1. ................ THE SICAV AND THE PARTIES CONCERNED 3 2. ................ INTRODUCTION 5 3. ................ DESCRIPTION OF THE SICAV 6 4. ................ OBJECTIVE OF THE SICAV 6 7 5. ................ ELIGIBLE INVESTMENTS 6. ................ INVESTMENT RESTRICTIONS 8 7. ................ RISKS ASSOCIATED WITH AN INVESTMENT IN THE SICAV 16 8. ................ MANAGEMENT COMPANY 20 21 9. ................ CUSTODIAN 10. .............. DESCRIPTION  OF  THE  SHARES,  RIGHTS  OF  THE  SHAREHOLDERS AND DISTRIBUTION POLICY 21 11. .............. SUBSCRIPTIONS, REDEMPTIONS, CONVERSIONS AND TRANSFERS  29 12. .............. FATCA OBLIGATIONS AND CONSTRAINTS 30 13. .............. DEFINITION AND CALCULATION OF THE NET ASSET VALUE 32 14. .............. TAXATION OF THE SICAV AND THE SHAREHOLDERS 32 15. .............. FINANCIAL REPORTS 33 16. .............. INFORMATION FOR SHAREHOLDERS 33 SUB-FUND FACTSHEETS ............................................................................................. 38 ARTICLES OF ASSOCIATION ..................................................................................... 109

No  parties  are  authorised  to  provide  information  other  than  that  contained  in  this  prospectus  and these articles of association as well as the documents mentioned herein.

2


<!-- page_num: 1 -->
---###### RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

####### 1.  THE SICAV AND THE PA RTIES CONCERNED

######## Name of the SICAV

RAM (LUX) SYSTEMATIC FUNDS

######## Registered office of the SICAV

14, boulevard Royal L-2449 LUXEMBOURG

######## Luxembourg Trade and Companies Register

B 90 383

######## number Legal structure

A  Luxembourg  Société  d'Investissement  à  Capital

Variable (SICAV – open-ended investment company)

with multiple sub-funds subject to Part I of the law of 17  December  2010  on  undertakings  for  collective

investment (the “Law of 2010”).

######## Board of Directors of the SICAV

Thomas de SAINT-SEINE Manager RAM Active Investments SA

Société anonyme (public limited company)

62, rue du Rhône CH-1204 GENEVA Chairman Roberto ZITO Head of Operations & Finance RAM Active Investments SA

Société anonyme (public limited company)

62, rue du Rhône CH-1204 GENEVA Director Philippe WAGENER Conducting Officer RAM Active Investments (Luxembourg) S.A.

Société anonyme (public limited company)

41, avenue de la Liberté L-1913 LUXEMBOURG Director Fernand REINERS Member of the Management Board BANQUE DE LUXEMBOURG

Société anonyme (public limited company)

14, boulevard Royal L 2449 LUXEMBOURG Director RAM ACTIVE INVESTMENTS (Luxembourg) S.A.

######## Management company of the SICAV

Société anonyme (public limited company)

41, avenue de la Liberté L-1931 LUXEMBOURG

######## Board of Directors of the Management

Thomas de SAINT-SEINE

######## Company

Manager RAM Active Investments SA

Société anonyme (public limited company)

62, rue du Rhône CH-1204 GENEVA Chairman

3


<!-- page_num: 2 -->
---######### RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

Philippe WAGENER Conducting Officer RAM Active Investments (Luxembourg) S.A.

Société anonyme (public limited company)

41, avenue de la Liberté L-1913 LUXEMBOURG Director Yves WAGNER Corporate Director

The Directors’ Office, Luxembourg

19, rue de Bitbourg L-1273 LUXEMBOURG Director

######## Directors of the Management Company

Philippe WAGENER Conducting Officer RAM Active Investments (Luxembourg) S.A.

Société anonyme (public limited company)

41, avenue de la Liberté L-1913 LUXEMBOURG Yves WAGNER Corporate Director

The Directors’ Office, Luxembourg

19, rue de Bitbourg L-1273 LUXEMBOURG

######## Name and registered office of the Investment

RAM Active Investments SA

######## Manager

Société anonyme (public limited company)

62, rue du Rhône CH-1204 GENEVA

######## Domiciliary agent

BANQUE DE LUXEMBOURG

Société anonyme (public limited company)

14, boulevard Royal L-2449 LUXEMBOURG

######## Custodian and Principal Paying Agent

BANQUE DE LUXEMBOURG

Société anonyme (public limited company)

14, boulevard Royal L-2449 LUXEMBOURG

######## Central Administration

BANQUE DE LUXEMBOURG

Société anonyme (public limited company)

14, boulevard Royal L-2449 LUXEMBOURG

######## Central Administration subcontractor

EUROPEAN FUND ADMINISTRATION

Société anonyme (public limited company)

2, rue d’Alsace

B.P. 1725 L-1017 LUXEMBOURG

######## Approved Independent Auditor

ERNST & YOUNG S.A. 7, rue Gabriel Lippman

2, Parc d’activité Syrdall

L-5365 MUNSBACH

4


<!-- page_num: 3 -->
---######### RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

########## 2. INTRODUCTION

Nobody is authorised to provide information, make declarations or give confirmations in relation to the  offer,  distribution,  subscription,  sale,  conversion  or  redemption  of  shares  of  the  SICAV  other than those indicated in the Prospectus. However, if such information, declarations or confirmations are given, they cannot be regarded as having been authorised by the SICAV. The provision of the Prospectus,  the  offer,  distribution,  conversion,  transfer,  subscription  or  issue  of  shares  of  the SICAV  do  not  imply  and  do  not  require  that  the  information  contained  in  the  Prospectus  remain correct after the date on which the Prospectus was provided, or shares of the SICAV were offered, placed, converted, transferred, subscribed or issued. Investing  in  shares  of  the  SICAV  entails  risks,  such  as  they  are  described  in  section  7  -  Risks associated with an investment in the SICAV.

The  providing  of  the  Prospectus  and  the  offering  or  purchase  of  the  SICAV’s  shares  may  be

prohibited or restricted in some jurisdictions. The Prospectus does not constitute an offer, invitation or  solicitation  to  subscribe  or  purchase  shares  of  the  SICAV  in  any  jurisdiction  in  which  such  an offer,  invitation  or  solicitation  is  unauthorised  or  would  be  illegal.  Any  person  in  any  jurisdiction whatsoever who receives the Prospectus shall not regard the fact of being given the Prospectus as constituting an offer, invitation or solicitation to subscribe or purchase shares of the SICAV unless, in the jurisdiction concerned, such offer, invitation or solicitation is authorised without application of legal or regulatory restrictions. Any person in possession of the Prospectus and any person wishing to subscribe or purchase shares of the SICAV shall be responsible for familiarising themselves and complying with the legal and regulatory provisions in the jurisdictions concerned.

########### Data protection

Pursuant to the obligations arising from the law of 2 August 2002 on the protection of individuals as

regards the processing of personal data, as amended (the “Law of 2 August 2002”), shareholders

are  advised  that  the  SICAV,  or  any  person  authorised  by  it,  shall  take  reasonable  measures  to ensure that the necessary formalities prior to processing data are followed.

Note that in this regard, European Fund Administration (“EFA”) processes personal data relating to the SICAV’s shareholders on the SICAV’s behalf. The EFA processes personal data relating to the SICAV’s shareholders using a computer database so that it can perform its tasks, and in particular:

-  open, close and freeze accounts in the name of the SICAV’s shareholders; -  manage  share  subscriptions,  redemptions,  conversions  and transfers  by  SICAV shareholders; -  send transaction confirmations to the SICAV’s shareholders; -  pay dividends to the SICAV’s shareholders; -  handle inheritance matters for the SICAV’s deceased shareholders. This personal data is not used for marketing purposes. This  personal  data  may  be  transferred  to  third  parties  only  on  the  written  instructions  of  the

SICAV’s  Board  of  Directors,  if  Luxembourg  law  so  requires,  or  on  the  written  instructions  of  the

shareholder. Shareholders are informed that they have the right to view this personal data and ask for it to be corrected if there is an error.

5


<!-- page_num: 4 -->
---############ RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

############# 3.  DESCRIPTION OF THE S ICAV

RAM  (LUX)  SYSTEMATIC  FUNDS  is  a  Luxembourg  open-ended  investment  company  (“SICAV”) with multiple sub-funds, subject to Part I of the Law of 2010. The  SICAV  was  created  on  19  December  2002  for  an  indefinite  term,  and  the  articles  of association  were  last  amended  by  the  extraordinary  general  meeting  of  28  October  2013.  The latest version of the coordinated text of the articles of association was published on 27 November 2013. The  consolidation  currency  is  the  euro  (EUR).  The  minimum  share  capital  of  the  SICAV  is  one million  two  hundred  and  fifty  thousand  euro  (EUR  1,250,000.00),  or  the  equivalent  amount  in another currency. The minimum share capital must be reached within a period of six months of the

SICAV’s approval. The SICAV’s financial year shall end on 31 December each year.

The following sub-funds are currently available for subscription:

############## Name Reference currency

RAM (LUX) SYSTEMATIC FUNDS – EUROPEAN EQUITIES EUR RAM (LUX) SYSTEMATIC FUNDS – NORTH AMERICAN EQUITIES USD RAM (LUX) SYSTEMATIC FUNDS – GLOBAL SHAREHOLDER YIELD USD EQUITIES RAM (LUX) SYSTEMATIC FUNDS – EMERGING MARKETS USD EQUITIES USD RAM (LUX) SYSTEMATIC FUNDS – EMERGING MARKETS CORE EQUITIES RAM (LUX) SYSTEMATIC FUNDS – LONG/SHORT EUROPEAN EUR EQUITIES RAM (LUX) SYSTEMATIC FUNDS – LONG/SHORT EMERGING USD MARKETS EQUITIES The  SICAV  reserves  the  right  to  create  new  sub-funds.  In  this  case  the  Prospectus  shall  be amended accordingly. The SICAV comprises a single legal entity. The assets of a sub-fund are exclusively liable for the rights of shareholders of that sub-fund and for those of creditors whose financial claim arises from the creation, operating or liquidation of that sub-fund.

############### 4.  OBJECTIVE OF THE SICAV

The  objective  of  the  SICAV  is  to  provide  shareholders  with  the  opportunity  to  benefit  from  the professional  management  of  portfolios  of  transferable  securities  and/or  other  financial  assets  as defined in the investment policy of each sub-fund (see sub-fund factsheets). An investment in the SICAV must be regarded as a medium to long-term investment. There is no guarantee that the SICAV will achieve its investment objectives. The SICAV’s investments are subject to the market’s normal fluctuations and to the risks inherent

in  any  investment;  there  is  no  guarantee  that  the  SICAV’s  investments  will  be  profitable.  The

SICAV intends to maintain a diversified investment portfolio in order to limit investment risks.

6


<!-- page_num: 5 -->
---################ RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

################# 5.  ELIGIBLE INVESTMENTS

1.

The SICAV’s investments consist of one or more of the following items:

a. transferable securities and money market instruments listed or traded on a regulated market within the meaning of Directive 2004/39/EC of the European Parliament and Council of 21 April 2004 concerning markets in financial instruments; b. transferable  securities  and  money  market  instruments  traded  on  another  regulated market  of  an  EU  Member  State,  which  operates  regularly  and  is  recognised  and open to the public; c. transferable  securities  and  money  market  instruments  admitted  to  an  official  listing on a stock exchange of a state that is not part of the EU or traded on another market of  a  state  that  is  not  part  of  the  EU,  which  is  regulated,  operates  regularly  and  is recognised and open to the public; d. recently issued transferable securities and money market instruments, provided that: - the  terms  of  issue  include  an  undertaking  that  an  application  will  be  made  for admission  to  official  listing  on  a  stock  exchange  or  another  regulated  market  that operates regularly, is recognised and open to the public; and -  such admission is secured within one year of the issue at the latest. e. units  of  UCITS  authorised  in  accordance  with  Directive  2009/65/EC  (“UCITS”), and/or other UCIs within the meaning of article 1, paragraph (2), points a) and b) of Directive 2009/65/EC, regardless of whether they are established in a Member State

of the European Union or not (“other UCIs”), provided that:

-  such other UCIs are authorised under  laws  that require that such undertakings  are subject to supervision considered by the CSSF to be equivalent to that laid down in Community law, and that cooperation between the authorities is sufficiently ensured; - the level of protection guaranteed to unitholders of these other UCIs is equivalent to that provided to the unitholders of a UCITS and, in particular, that the rules relating to  the  division  of  assets  and  to  the  borrowing,  lending  and  short  selling  of transferable  securities  and  money  market  instruments  are  equivalent  to  the requirements of Directive 2009/65/EC; - the  business  of  these  other  UCIs  is  reported  in  semi-annual  and  annual  reports  to enable  an  assessment  to  be  made  of  the  assets  and  liabilities,  income  and operations over the reporting period; - the proportion of net assets that these UCITS or other UCIs in which units are to be acquired can invest, in accordance with their management regulations or articles of association, in units of other UCITS or UCIs does not exceed 10% in total; f. deposits with credit institutions, which are repayable on demand or have the right to be withdrawn and have a maturity of less than or equal to 12 months, provided that the  credit  institution  has  its  registered  office  in  a  Member  State  of  the  European Union or, if the registered office of the credit institution is situated in another State, provided  that  it  is  subject  to  prudential  rules  considered  by  the  CSSF  to  be equivalent to those laid down in Community law; g. derivative financial instruments, including equivalent cash-settled instruments, traded on a regulated market referred to in points a), b) and c) above, or derivative financial instruments traded over-the-counter ("OTC derivatives"), provided that: - the  underlying  instruments  are  those  covered  in  this  point  1,  financial  indices, interest rates, foreign exchange rates or currencies, in which the SICAV may invest according to its investment objectives, as defined in  this Prospectus and its articles of association;

7


<!-- page_num: 6 -->
---################## RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds

- the  counterparties  to  OTC  derivative  transactions  are  institutions  subject  to prudential supervision and belonging to a category approved by the CSSF; and - the OTC derivatives are subject to reliable and verifiable valuation on a daily basis, and can be sold, liquidated or closed by an offsetting transaction at any time at their

fair value at the SICAV’s initiative;

h. money  market  instruments  other  than  those  traded  on  a  regulated  market  and mentioned  in  article  1  of  the  Law  of  2010,  provided  that  the  issue  or  the  issuer  of these  instruments  is  subject  to  regulations  aimed  at  protecting  investors  and  their savings and that these instruments are: - issued or guaranteed by a central, regional or local government administration, by a central  bank  of  an  EU  Member  State,  by  the  European  Central  Bank,  by  the European Union or by the European Investment Bank, by another country or, in the case of a federal state, by a member of the federation, or by an international public body to which one or several Member States belong, or - issued by a company whose securities are traded on the regulated markets listed in points a, b or c above, or issued or guaranteed by an institution subject to prudential supervision according to the criteria stipulated by EU Law, or by an institution subject and  conforming  to  prudential  rules  which  Luxembourg's  financial  supervisory authority,  the  CSSF,  considers  at  least  as  stringent  as  those  prescribed  by  EU legislation; or - issued by other entities belonging to categories approved by the CSSF provided that investments  in  such  instruments  are  subject  to  rules  for  protecting  investors  which are  equivalent  to  those  stipulated  under  the  first,  second  and  third  bullet  points above, and that the issuer is either a company with capital and reserves amounting to at least ten million euro  (EUR 10,000,000) and  which presents and publishes its annual  accounts  in  accordance  with  the  fourth  directive  78/660/EEC,  or  an  entity which,  within  a  group  of  companies  including  one  or  more  listed  companies,  is devoted  to  financing  the  group,  or  an  entity  devoted  to  financing  securitisation vehicles backed by bank financing. 2. However, the SICAV may not: invest more than 10% of its net assets in transferable securities and money market a. instruments other than those specified in point 1 of this section; b. purchase precious metals or certificates representing precious metals. 3. The SICAV may: a. acquire movable and immovable assets essential for carrying out its business; b. hold cash, on an incidental basis.

################### 6. INVESTMENT RESTRICTI ONS

The following criteria and restrictions must be observed by each of the SICAV’s sub-funds:

#################### Restrictions relating to transferable securities and money market instruments

1. a. The  SICAV  may  not  invest  more  than  10%  of  its  net  assets  in  transferable securities or money market instruments issued by a single entity. It may not invest more than 20% of its net assets in deposits with a single institution. The SICAV’s counterparty risk exposure in an over-the-counter derivatives  transaction may  not exceed  10%  of  its  net  assets  when  the  counterparty  is  a  credit  institution  as referred to in section 5 point 1.f) below, or 5% of its net assets in other cases.

8


<!-- page_num: 7 -->
---##################### RAM (LUX) SYSTEMATIC FUNDS Luxembourg SICAV with multiple sub-funds


# Упаковка в один класс

In [18]:
class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, regions, output_model:LogicTreeModel):
        reg_page = [[]]
        tmp_page = 0
        for reg in regions:
            if tmp_page == reg['metainfo']["page"]:
                reg_page[tmp_page].append(reg)
            else:
                reg_page.append([reg])
                tmp_page += 1
            
        document = Document([Page(regions=[Region(r) for r in regs], num_page=num) for num, regs in enumerate(reg_page)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree

class ExtractTree:
    def __init__(self):
        self.creater = CustomJson2LogicTree()
        self._font_from_doc = {}
        self._list_font_type = []

        
    def extract(self, tree:LogicTreeModel):
        doc_rows = [row for page in tree.document.pages for row in page.rows]
        row_num_page = [page.num_page for page in tree.document.pages for _ in page.rows]
        clusters = self.get_cluster(doc_rows)
        level_header_cluster = self.get_level_header(clusters)
        regions = self.get_regions(doc_rows, row_num_page, level_header_cluster)
        self.creater.upload(regions, tree)


    def get_regions(self, doc_rows, row_num_page, level_header_cluster):
        num_cluster = [ self._font_from_doc[vec] for vec in self._list_font_type]
        regions = []
        
        def get_region(row, cl, num_page):
            tmp_reg = {
                "rows": [row],
                "label": "header" if cl in level_header_cluster else "text",
                "metainfo": {"page": num_page}
            }
            if cl in level_header_cluster:
                tmp_reg["header_level"] = level_header_cluster[cl]
            return tmp_reg
        
        tmp_cl = num_cluster[0]
        tmp_num_page = 0
        tmp_reg = get_region(rows[0].to_dict(), tmp_cl, tmp_num_page)
        for row, cl, num_page in zip(doc_rows[1:], num_cluster[1:], row_num_page[1:]):
            if cl == tmp_cl and num_page==tmp_num_page:
                tmp_reg['rows'].append(row.to_dict())
            else:
                regions.append(tmp_reg.copy())
                tmp_cl = cl
                tmp_num_page = num_page
                tmp_reg = get_region(row.to_dict(), cl,num_page)
        return regions
        
    def get_level_header(self, clusters):
        main_clust, main_font = self.get_main_cluster(clusters)
        header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > main_font}
        header_cluster_index = list(header_cluster.keys())
        header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)        
        level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
        return level_header_cluster
        
    def get_main_cluster(self, clusters):
        max_clust = -1
        max_size = 0
        for ind, rows in clusters.items():
            if max_size < len(rows):
                max_clust = ind
                max_size = len(rows)
        font_text =  clusters[max_clust][0].font

        font_text.to_dict()
        return max_clust, font_text

    def get_cluster(self, doc_rows):
        self._font_from_doc = {}
        self._list_font_type = []
        def get_vec_feature(row):
            fd = row.font.to_dict()
            name = fd['name']
            size = int(round(fd['size']/2))
            width = int(round(fd['width']/0.1))
            italic = int(round(fd['italic']/0.1))
            return (name, size, width, italic)
        
        def get_id_exist_cluster(feature):
            self._list_font_type.append(feature)
            if feature in self._font_from_doc.keys():
                 return self._font_from_doc[feature] 
            return None
                
        def add_new_cluster(feature):
            indexs= list(self._font_from_doc.values())
            index = max(indexs)+1 if len(indexs) != 0 else 0
            self._font_from_doc[feature] = index
            clusters[index] = []
            return index
            
        clusters = {}
        for row in doc_rows:
            feature_row = get_vec_feature(row)
            index = get_id_exist_cluster(feature_row)
            if index is None:
                index = add_new_cluster(feature_row)
            clusters[index].append(row)
        return clusters
        
       
     
   

extract_tree=ExtractTree()

In [19]:
def tree2fintoc_json(doc_tree) -> Dict:
    fintoc_json = []
    for id_node, node in doc_tree['nodes']['regions'].items():
        if node['label'] == 'header':
            reg = {
                "text":node['text'],
                "id": id_node,
                "page": node['metainfo']['page'] + 1, # В PageR специально оставил нумерацию с нуля (поскольку номер определяется не порядком, а пишится на странице и это еще не реализовано)
                "depth": node['header_level']
            }
            fintoc_json.append(reg)
    return fintoc_json

N = len(FILE_PATHS)
for i, file_path in enumerate(FILE_PATHS):    
    pdf_reader.read_from_file(file_path)
    pdf_reader.extract()
    pdf2tree.convert(pdf_reader, tree)
    extract_tree.extract(tree)
    
    doc_tree = tree.to_dict()
    pred_path = FINTOC_EN_PRED/(file_path.name+'.'+JSON_EXTENSION)
    # print(tree.document.md)
    
    rez = tree2fintoc_json(doc_tree)
    with open(pred_path, 'w') as f:
        json.dump(rez, f)

    print(f'{i+1}/{N} ({(i+1)/N*100:.2f}%)')

1/10 (10.00%)
2/10 (20.00%)
3/10 (30.00%)
4/10 (40.00%)
5/10 (50.00%)
6/10 (60.00%)
7/10 (70.00%)
8/10 (80.00%)
9/10 (90.00%)
10/10 (100.00%)

In [21]:
import subprocess
import pandas as pd

In [22]:
subprocess.run(['python3.13', 'metric.py', '--gt_folder', FINTOC_EN_ANNOTS, '--submission_folder', FINTOC_EN_PRED])
df = pd.read_csv('td_report.csv', delimiter='\t')
df[-2:-1][['Prec', 'Rec', 'F1']]

                   Prec                 Rec                  F1
141  0.5743920470084717  0.7690840319930897  0.6338382920067585

In [23]:
df = pd.read_csv('toc_report.csv', delimiter='\t')
tbl = df[-4:-3]
tbl[['Inex08-P', 'Inex08-R', 'Inex08-F1', 'Inex08-Title acc', 'Inex08-Level acc']]

    Inex08-P Inex08-R Inex08-F1 Inex08-Title acc Inex08-Level acc
159     40.0     48.2      42.5             55.2             17.3