In [2]:
from dotenv import load_dotenv
import os
from pathlib import Path
load_dotenv()
PATH_FINTOC_2022 = Path(os.getenv('PATH_FINTOC_2022'))

In [2]:
FINTOC_EN = PATH_FINTOC_2022/'data'/'en'
FINTOC_EN_PDF =FINTOC_EN/'pdf'
FINTOC_EN_ANNOTS = FINTOC_EN/'annots'
FINTOC_EN_PRED = FINTOC_EN/'preds'

JSON_EXTENSION = "fintoc4.json"

In [3]:
if not FINTOC_EN_PRED.exists():
    FINTOC_EN_PRED.mkdir()
FILE_PATHS = list(FINTOC_EN_PDF.iterdir())[:10]

In [4]:
import json

import pager
from pager.pager_pipe_line import pdf2region_row

from pager.doc_model import MinerPDFModel
from pager.doc_model import LogicTreeModel
from pager.doc_model.converters import PDF2LogicTree
from pager.doc_model.dtype import Document, Page
from pager import Region

from typing import Dict

pdf_reader = MinerPDFModel({"page_model": pdf2region_row})
pdf2tree = PDF2LogicTree()
tree = LogicTreeModel()

In [5]:
file_path = FILE_PATHS[0]
pdf_reader.read_from_file(file_path)
pdf_reader.extract()
pdf2tree.convert(pdf_reader, tree)
file_path

/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch_geometric/nn/conv/tag_conv.py:102: UserWarning: Converting sparse tensor to CSR format for more efficient processing. Consider converting your sparse tensor to CSR format beforehand to avoid repeated conversion (got 'torch.sparse_coo')
  return spmm(adj_t, x, reduce=self.aggr)
/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch_geometric/utils/_spmm.py:71: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  src = src.to_sparse_csr()
/home/daniil/project/PageR/env/lib/python3.12/site-packages/torch/nn/modules/module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)

PosixPath('/home/dataset/fintoc2022/data/en/pdf/LU0066480616-LU0208183011_English_2012_ValartisRussianMarketFund.pdf')

# Отладка на одном документе

In [6]:
doc_rows = [row for page in tree.document.pages for row in page.rows]
row_num_page = [page.num_page for page in tree.document.pages for _ in page.rows]

In [7]:
# for row in doc_rows:
#     print(row.text)

### Кластер строк

In [8]:
_font_from_doc = {}
_list_font_type = []
def get_vec_feature(row):
    fd = row.font.to_dict()
    name = fd['name']
    size = int(round(fd['size']/2))
    width = int(round(fd['width']/0.1))
    italic = int(round(fd['italic']/0.1))
    return (name, size, width, italic)

def get_id_exist_cluster(feature):
    _list_font_type.append(feature)
    if feature in _font_from_doc.keys():
         return _font_from_doc[feature] 
    return None
        
def add_new_cluster(feature):
    indexs= list(_font_from_doc.values())
    index = max(indexs)+1 if len(indexs) != 0 else 0
    _font_from_doc[feature] = index
    clusters[index] = []
    return index
    
clusters = {}
for row in doc_rows:
    feature_row = get_vec_feature(row)
    index = get_id_exist_cluster(feature_row)
    if index is None:
        index = add_new_cluster(feature_row)
    clusters[index].append(row)

### Поиск кластера основного текста

In [9]:
max_clust = -1
max_size = 0
for ind, rows in clusters.items():
    if max_size < len(rows):
        max_clust = ind
        max_size = len(rows)
font_text =  clusters[max_clust][0].font
print(max_size)
font_text.to_dict()

1569

{'name': 'Helvetica', 'width': 0.0, 'italic': 0.0, 'size': 9.694196122319966}

### Поиск кластеров заголовков

In [10]:
header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > font_text}

### Сортировка кластеров заголовков

In [11]:
header_cluster_index = list(header_cluster.keys())
header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)
for header_ind in header_cluster_index:
    print(get_vec_feature(header_cluster[header_ind]))

level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
# level_header_cluster

('Helvetica-Bold', 9, 10, 0)
('Helvetica-Bold', 8, 10, 0)
('Helvetica-Bold', 7, 10, 0)
('Helvetica-Bold', 6, 10, 0)
('Helvetica-Bold', 5, 10, 0)
('Helvetica-BoldOblique', 5, 10, 0)
('Helvetica-Bold', 4, 10, 0)

### Создание регионов

In [12]:
num_cluster = [ _font_from_doc[vec] for vec in _list_font_type]
regions = []

def get_region(row, cl, num_page):
    tmp_reg = {
        "rows": [row],
        "label": "header" if cl in level_header_cluster else "text",
        "metainfo": {"page": num_page}
    }
    if cl in level_header_cluster:
        tmp_reg["header_level"] = level_header_cluster[cl]
    return tmp_reg

tmp_cl = num_cluster[0]
tmp_num_page = 0
tmp_reg = get_region(rows[0].to_dict(), tmp_cl, tmp_num_page)
for row, cl, num_page in zip(doc_rows[1:], num_cluster[1:], row_num_page[1:]):
    if cl == tmp_cl and num_page==tmp_num_page:
        tmp_reg['rows'].append(row.to_dict())
    else:
        regions.append(tmp_reg.copy())
        tmp_cl = cl
        tmp_num_page = num_page
        tmp_reg = get_region(row.to_dict(), cl,num_page)

### Построение дерева (Переиспользование класса конвертера)

In [13]:


class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, regions, output_model:LogicTreeModel):
        reg_page = [[]]
        tmp_page = 0
        for reg in regions:
            if tmp_page == reg['metainfo']["page"]:
                reg_page[tmp_page].append(reg)
            else:
                reg_page.append([reg])
                tmp_page += 1
            
        document = Document([Page(regions=[Region(r) for r in regs], num_page=num) for num, regs in enumerate(reg_page)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree


creater = CustomJson2LogicTree()
tree = LogicTreeModel()
creater.upload(regions, tree)

In [14]:
print(tree.document.md)

# Distributor).    The  Distributor  is  entitled  to  delegate  its  functions  to  one  or  more  other  persons

L'apposition du visa ne peut en aucun cas servir d'argument de publicité Luxembourg, le 2012-10-08 Commission de Surveillance du Secteur Financier

# VALARTIS RUSSIAN MARKET FUND

an investment company with variable capital (société d’investissement à capital variable) organised as an undertakings for collective investment in transferable securities (organisme de placement collectif en valeurs mobilières) incorporated in and under the laws of the Grand Duchy of Luxembourg

VAT Registration No. LU21668963

## PROSPECTUS

### 25 SEPTEMBER 2012


<!-- page_num: 0 -->
---### CONTENTS

1.  MANAGEMENT AND ADMINISTRATION ............................................................................................. 6 2.  DEFINITIONS ........................................................................................................................................ 8 3.  PRINCIPAL FEATURES ...................................................................................................................... 10 4. INTRODUCTION ................................................................................................................................. 12 5. INVESTMENT OBJECTIVES AND POLICY........................................................................................ 13 6. INVESTMENT RESTRICTIONS .......................................................................................................... 15 7.  TECHNIQUES & INSTRUMENTS ....................................................................................................... 22 8.  PREVENTION  OF  MONEY  LAUNDERING  AND  AGAINST  TERRORISM  FINANCING REGULATIONS ................................................................................................................................... 26 9.  APPLICATIONS AND REDEMPTIONS ............................................................................................... 28 10.  VALUATIONS, FEES AND EXPENSES .............................................................................................. 33 11.  MANAGEMENT ................................................................................................................................... 38 12.  CUSTODIAN ........................................................................................................................................ 40 13.  DOMICILIARY, REGISTRAR AND TRANSFER AND ADMINISTRATIVE AGENT ............................ 41 14.  DISTRIBUTION AGREEMENT ............................................................................................................ 42 15.  TAXATION ........................................................................................................................................... 43 16.  RISK FACTORS .................................................................................................................................. 45 17.  DIVIDEND POLICY .............................................................................................................................. 48 18.  GENERAL AND STATUTORY INFORMATION .................................................................................. 49 19.  LIQUIDATION ...................................................................................................................................... 54 20.  MERGERS OF CLASSES OF SHARES ............................................................................................. 55 21.  CONFLICTS OF INTEREST ................................................................................................................ 56

Valartis Russian Market Fund 2/58


<!-- page_num: 1 -->
---Valartis Russian Market Fund (the SICAV) is a société anonyme which was incorporated under the laws of

the Grand Duchy of Luxembourg as a société d’investissement à capital variable and under the name The MC  Russian  Market  Fund.  The  change  of  the  name  of the  SICAV from "The MC Russian Market  Fund" into  "Valartis  Russian  Market  Fund"  was  approved  by  the  Shareholders  at  an  extraordinary  general meeting held on the 25th of September 2012. The SICAV is subject to Part I of the law of 17 December

2010 relating to undertakings collective investment (the 2010 Law).

The  SICAV  complies  with  article  27  of  the  2010  Law.  The  SICAV  did  not  designate  a  management company. The Board of Directors of the SICAV is responsible for the information contained in this Prospectus. To the best of the knowledge and belief of the Directors (who have taken all reasonable care to ensure that it is the  case)  the  information  contained  in  this  document  is  in  accordance  with  the  facts  and  does  not  omit anything likely to affect the import of such information. The Shares in the SICAV are offered solely on the basis of the information and representations contained in  this  Prospectus  and  any  further  information  given or  representations  made by any person may not be relied upon as having been authorised by the SICAV or its Directors. Neither the delivery of this document nor the allotment  or issue of Shares shall under any circumstances create any implication that there has been no change in the affairs of the SICAV since the date hereof. This Prospectus does not constitute an offer or solicitation to any person in any jurisdiction in which such offer or solicitation is not authorised or to any person to whom it would be unlawful to make such offer or solicitation.  The  distribution  of  this  Prospectus  and  the  offering  of  Shares  in  certain  jurisdictions  may  be restricted  and,  accordingly,  persons  into  whose  possession  this  document  comes  are  required  to  inform themselves about, and to observe, such restrictions. Prospective investors should inform themselves as to (a) the legal requirements within their own jurisdictions for the purchase, holding or disposal of Shares in the SICAV, (b) any foreign exchange restrictions which may affect them, and (c) the income and other tax consequences which may apply in their own jurisdictions relevant to the purchase, holding or disposal of Shares in the SICAV. No person is authorised to give any information or to make any representation other than those contained in this Prospectus, or in the documents referred to in the Prospectus and which can be consulted by the public. A Key Investor Information Document (KIID) for each Class of Shares available must be made available to investors free of charge prior to any subscription for Shares. Prospective investors must consult the KIID pertaining  to  the  relevant  Class  of  Shares  in  which  they  intend  to  invest.  Requests  for  subscription  or conversion  of  Shares  will  be  accepted  upon  verification  by  the  Board  of  Directors  that  the  (prospective) Shareholder  has the  Promotor  at relevant  KIID  available  on the  website  of received the www.valartisfunds.ch or free of charge at the registered office of the SICAV during normal business hours on any Business Day. Subscriptions  can  be  accepted  only  on  the  basis  of  the  current  Prospectus,  which  is  valid  only  if accompanied  by  a  copy  of  the  latest  SICAV's  annual  report  containing  its  audited  accounts,  and  of  the

Valartis Russian Market Fund 3/58


<!-- page_num: 2 -->
---semi-annual  report  if  this  was  published  after  the  SICAV’s  latest  annual  report.  These  reports  form  an integral part of the present Prospectus. If you are in doubt about the contents of this Prospectus or about your position in relation to the acquisition, holding, disposal or receipt of distributions in respect of shares you should consult your stockbroker, bank manager, solicitor, accountant or other professional adviser. The  SICAV  is  not  a  recognised  collective  investment  scheme  for  the  purposes of the Financial Services

Act 1986 of the United Kingdom (the 1986 Act). This Prospectus may only be issued or passed on in the

United  Kingdom  to  persons  falling  within  the  scope  of  Article  11(3)  of  the  Financial  Services  Act  1986 (Investment  Advertisements)  (Exemptions)  Order  1995  and  the  Shares  in  the  SICAV  may  only  be promoted  in  the  United  Kingdom  by  an  authorised  person  under  the  1986  Act  in  accordance  with  the Financial Services (Promotion of Unregulated Schemes) Regulations 1991 as from time to time amended. The Shares in the SICAV have not been and will not be registered under the United States Securities Act

of  1933,  as  amended  (the  1933  Act)  or  under  any  other  laws  of  any  state  of  the  United  States  and,

therefore, the Shares may neither be offered, sold or transferred in the United States of America (included its territories and possessions), nor benefit directly or indirectly to a US Person. The Shares in the SICAV being offered hereby have not been approved or recommended by the United States Securities Exchange

Commission (the  SEC) or  any state  of the United States or other governmental authority and neither the

SEC  nor  any  such  authority  has  passed  upon  the  accuracy  or  adequacy  of  this  document.  The  non-US financial  institutions  not  participating  to  the  FATCA  program  or  to  similar  program  set  up  by  partner countries  having signed an agreement with the United States of America, may be  subject to compulsory redemption of their shares at the entry in force and following the terms of such program. The  SICAV  is  not  and  will  not  be  registered  under  United  States  Investment  Company  Act  of  1940,  as

amended  (the  1940  Act).  Based  on  interpretations  of  the  1940  Act  by  the  staff  of  the  SEC  relating  to

foreign investment companies, if the SICAV has more than 100 beneficial owners who are US Persons, it may become subject to the 1940 Act. The Directors will not knowingly permit the number of Shareholders who are US Persons to be more than 80. The Investment Manager will not be registered under the 1940 Act. The attention of US Persons is drawn to the compulsory redemption powers mentioned in Clause 9 of this Prospectus. The  Shares  are  subject  to  restrictions  on  transferability  and  resale  and may not be transferred  or resold except as permitted under the 1933 Act, and the applicable state securities laws, pursuant to registration or exemption therefrom (for example, to qualified institutional buyers in reliance on Regulation 144A or to non-US Persons in offshore transactions in reliance on Regulation S under the 1933 Act). Investors should be aware that they could be required to bear the financial risks of this investment until the SICAV is wound up. The Shares will not be offered in Russia to Russian residents as such offer may require the authorization of the relevant Russian authorities for the transfer of capital and neither the Shares in the SICAV nor this document have been registered in Russia under Russian federal or local laws for the purposes of selling Shares in Russia to Russian residents.

Valartis Russian Market Fund 4/58


<!-- page_num: 3 -->
---The  registration  of  the  SICAV  pursuant  to  the  2010  Law  does  not  require  any  Luxembourg  authority  to approve  or  disapprove  either  the  adequacy  of  this  Prospectus  or  the  portfolio  of  securities  held  by  the SICAV.  Any  representation  to  the  contrary  is  unauthorised  and  unlawful.  The  above  information  is  for general  guidance  only.  Prospective  applicants  for  Shares  should  inform  themselves  as  to  the  legal requirements applying, any  applicable exchange control regulations and applicable taxes in the countries of their respective citizenship, residence or domicile. Prospective investors’ attention is also drawn to Clause 16. The personal data of the subscriber and/or distributor are handled by KBL European Private Bankers S.A., Kredietrust Luxembourg S.A. and European Fund Administration S.A. (EFA) to enable them to manage the SICAV administratively and commercially, to enable operations to be handled pursuant to the stipulations of the Prospectus and the service contracts, to ensure that payments received are correctly assigned, that general  meetings  are  held  correctly  and  shareholder  certificates  correctly  drawn  up  if  necessary.  The subscriber or distributor has the right to access his/her data in order to modify, correct or update them. The SICAV draws the investors’ attention to the fact that any investor will only be able to fully exercise his investor rights directly against the SICAV, notably the right to participate in general shareholders’ meetings if  the  investor  is  registered  himself  and  in  his  own  name  in  the  shares’  register  of  the  SICAV.  In  cases where an investor invests in the SICAV through an intermediary investing into the SICAV in his own name but on behalf of the investor, it may not always be possible for the investor to exercise certain shareholder rights directly against the SICAV. Investors are advised to take advice on their rights.

Valartis Russian Market Fund 5/58


<!-- page_num: 4 -->
---### 1. MANAGEMENT AND ADMINISTRATION

#### Board of Directors

Philipp LEIBUNDGUT Valartis Bank AG Chairman Sihlstrasse 24 CH-8001 Zürich Walter FETSCHERIN Former Swiss Ambassador to Director Russia André HEUSSER Valartis Bank S.A. Director 2-4, Place du Molard CH-1211 Geneva André SCHMIT Kredietrust Luxembourg S.A. Director 11, Rue Aldringen L - 1118 Luxembourg Bernhard BOLLIGER Valartis Bank AG Director Sihlstrasse 24 CH-8001 Zürich André SCHMIT Kredietrust Luxembourg S.A.

#### Conducting Officers

11, Rue Aldringen

#### (Délégués à la

L - 1118 Luxembourg

#### gestion journalière)

Bernhard BOLLIGER Valartis Bank AG Sihlstrasse 24 CH-8001 Zürich

#### Investment

Valartis Bank AG Sihlstrasse 24

#### Manager

CH-8001 Zürich

#### Distributor

RG Hodge Plaza, 3rd Floor

#### Investment Adviser

Valartis International Ltd Wickhams Cay 1 Road Town, Tortola British Virgin Islands

#### Custodian

KBL European Private 43, boulevard Royal

#### Principal Paying

Bankers S.A. L-2955 Luxembourg

#### Agent

Valartis Russian Market Fund 6/58


<!-- page_num: 5 -->
---Kredietrust Luxembourg S.A. 11, rue Aldringen

#### Domiciliary Agent

L-2960 Luxembourg

#### Registrar and Transfer Agent Administrative Agent Auditor

Ernst & Young 6, rue Jean Monnet L-2180 Luxembourg

Valartis Russian Market Fund 7/58


<!-- page_num: 6 -->
---### 2. DEFINITIONS

#### Articles

The Articles of Incorporation of the SICAV

#### Board of Directors

The board of directors of the SICAV

#### Business Day

Any day on which banks are open for business in all of London, Luxembourg-City, Moscow, and Geneva

#### Class of Shares

Class  A,  Class  B,  Class  C  and  Class  D  Shares  differentiating themselves by their fee structure, minimum investment level and their currency

#### CSSF

Commission  de  Surveillance  du  Secteur  Financier,  regulatory

body of the financial sector in Luxembourg

#### EUR

The  currency  of  the  European  Union  Member  States  who  have adopted the Single Currency.

#### Euroclear System

Clearing system for Subscriptions and Redemptions

#### Hire Act

The  US  “Hiring  Incentives  to  Restore  Employment  Act”  of  18 April 2010

#### Issue Price

The price at which the Shares in the SICAV are issued

#### Moody’s

Moody’s Investor Services, Inc.

Net  Asset  Value  or

The Net Asset Value of the SICAV calculated in accordance with

#### NAV

the provisions of the Articles

#### OECD

Organisation for Economic Co-operation and Development

#### Redemption Price

The  price  per  Share  at  which  Shares  in  the  SICAV  are redeemed, calculated as described in Clause 9

#### Regulated Market

A  market  functioning  regularly,  which  is  regulated,  recognized and open to the public, as defined in the Directive 2004/39/EC on markets in financial instruments

#### Russian  Federation

Those regions, territories, republics, areas and cities which from

or Russia

time  to  time  constitute  the  geographic  area  recognised  as “Russia”

Valartis Russian Market Fund 8/58


<!-- page_num: 7 -->
---#### Russian Companies

Those  corporations,  joint  stock  companies,  economic  societies, trusts  and  other  entities  created,  registered  and  otherwise established  in  the  Russian  Federation  and  those  created, registered  and  otherwise  established  outside the  Russian Federation  operating  or  investing  primarily  in  the  Russian Federation  or  deriving  a  preponderant  part  of  their  income from the Russian Federation

#### S & P

Standard & Poor’s Ratings Group, a division of McGraw-Hill, Inc.

#### Shares

Shares in the SICAV of no par value

#### Shareholder

A holder of Shares as recorded in the SICAV’s register of Shares

#### UCI

Undertaking  for  collective  investment  within  the  meaning  of  the 2010 Law

#### UCITS

Undertaking  for  collective  investment  in  transferable  securities within the meaning of the 2010 Law

#### United States

The United States of America, any state, territory, or possession thereof,  any  area  subject  to  its  jurisdiction,  the  District  of Columbia, or any enclave of the United States Government or its agencies or instrumentalities

USD or US$

The currency of the United States

#### US Person

Has  the  meaning  ascribed  to  such  term  in  the  Regulation  S  of the 1933 Act and include US entities and US resident individuals as  construed  under  the  Hire  Act  and  implementing  regulations known under the acronym FATCA

Valartis Russian Market Fund 9/58


<!-- page_num: 8 -->
---### 3. PRINCIPAL FEATURES

The  following  is  a  summary  of  the  principal  features  of  the  SICAV  and  should  be  read  in conjunction with the full text of this Prospectus from which it is derived.

#### The SICAV

The SICAV is an open-ended investment company incorporated in Luxembourg on 13 May 1996. The Shares in the SICAV are listed on It  qualifies  as  an the  Luxembourg  Stock  Exchange. UCITSunder Part I of the 2010 Law.

#### Investment

The  investment  objective  of  the  SICAV  is  to  achieve  long-term

#### Objective

capital  appreciation  through  investing  in  Russian  Companies,  as well  as  companies  in  Eastern  Europe,  the  C.I.S.  and  elsewhere within the limits set forth in Clause 6.

#### Subscriptions  and

Shares  may  be  offered  on  each  Business  Day  at  the  Issue  Price

#### Redemptions

and redeemed on any Business Day at the prevailing Redemption Price. The minimum subscription is for:

#### Class of Shares Minimum subscription amount

Class A Shares USD 250,000.- Class B Shares USD 10,000.- Class C Shares EUR 250,000.- Class D Shares USD 1,000,000.- This minimal amount may be waived at the discretion of the Board of Directors. Details of  additional charges payable on the issue of Shares are set out in Clause 9. Capital gains, interest, dividends and other income received will be

#### Dividend Policy

automatically  reinvested,  and  no  dividend  will  be  paid to shareholders,  as  it  is  the  SICAV’s  objective  to  achieve  long  term capital  appreciation.  Nonetheless,  the  Board  of  Directors  may decide  to  propose  a  dividend  to  the  general  meeting  of  the shareholders if the Board of Directors deems this to be in their best interest,  due  for  example  to  changes  in  the  macroeconomic  or fiscal environment. Under  current  Luxembourg  law,  the  SICAV  will  not  be  liable  to

#### Taxation


# Упаковка в один класс

In [6]:
class CustomJson2LogicTree(PDF2LogicTree):
    def upload(self, regions, output_model:LogicTreeModel):
        reg_page = [[]]
        tmp_page = 0
        for reg in regions:
            if tmp_page == reg['metainfo']["page"]:
                reg_page[tmp_page].append(reg)
            else:
                reg_page.append([reg])
                tmp_page += 1
            
        document = Document([Page(regions=[Region(r) for r in regs], num_page=num) for num, regs in enumerate(reg_page)])
        regions = [reg for page in document.pages for reg in page.regions]
        tree = self.get_tree_from_doc(regions)
        self.set_level(regions, tree['parent'])
        
        output_model.document = document
        output_model.regions = regions
        output_model.edges = tree

class ExtractTree:
    def __init__(self):
        self.creater = CustomJson2LogicTree()
        self._font_from_doc = {}
        self._list_font_type = []

        
    def extract(self, tree:LogicTreeModel):
        doc_rows = [row for page in tree.document.pages for row in page.rows]
        row_num_page = [page.num_page for page in tree.document.pages for _ in page.rows]
        clusters = self.get_cluster(doc_rows)
        level_header_cluster = self.get_level_header(clusters)
        regions = self.get_regions(doc_rows, row_num_page, level_header_cluster)
        self.creater.upload(regions, tree)


    def get_regions(self, doc_rows, row_num_page, level_header_cluster):
        num_cluster = [ self._font_from_doc[vec] for vec in self._list_font_type]
        regions = []
        
        def get_region(row, cl, num_page):
            tmp_reg = {
                "rows": [row],
                "label": "header" if cl in level_header_cluster else "text",
                "metainfo": {"page": num_page}
            }
            if cl in level_header_cluster:
                tmp_reg["header_level"] = level_header_cluster[cl]
            return tmp_reg
        
        tmp_cl = num_cluster[0]
        tmp_num_page = 0
        tmp_reg = get_region(doc_rows[0].to_dict(), tmp_cl, tmp_num_page)
        for row, cl, num_page in zip(doc_rows[1:], num_cluster[1:], row_num_page[1:]):
            if cl == tmp_cl and num_page==tmp_num_page:
                tmp_reg['rows'].append(row.to_dict())
            else:
                regions.append(tmp_reg.copy())
                tmp_cl = cl
                tmp_num_page = num_page
                tmp_reg = get_region(row.to_dict(), cl,num_page)
        return regions
        
    def get_level_header(self, clusters):
        main_clust, main_font = self.get_main_cluster(clusters)
        header_cluster = {ind: cl[0] for ind, cl in clusters.items() if cl[0].font > main_font}
        header_cluster_index = list(header_cluster.keys())
        header_cluster_index.sort(key=lambda ind: header_cluster[ind].font, reverse=True)        
        level_header_cluster = {cl:level+1 for level, cl in enumerate(header_cluster_index)}
        return level_header_cluster
        
    def get_main_cluster(self, clusters):
        max_clust = -1
        max_size = 0
        for ind, rows in clusters.items():
            if max_size < len(rows):
                max_clust = ind
                max_size = len(rows)
        font_text =  clusters[max_clust][0].font

        font_text.to_dict()
        return max_clust, font_text

    def get_cluster(self, doc_rows):
        self._font_from_doc = {}
        self._list_font_type = []
        def get_vec_feature(row):
            fd = row.font.to_dict()
            name = fd['name']
            size = int(round(fd['size']/2))
            width = int(round(fd['width']/0.1))
            italic = int(round(fd['italic']/0.1))
            return (name, size, width, italic)
        
        def get_id_exist_cluster(feature):
            self._list_font_type.append(feature)
            if feature in self._font_from_doc.keys():
                 return self._font_from_doc[feature] 
            return None
                
        def add_new_cluster(feature):
            indexs= list(self._font_from_doc.values())
            index = max(indexs)+1 if len(indexs) != 0 else 0
            self._font_from_doc[feature] = index
            clusters[index] = []
            return index
            
        clusters = {}
        for row in doc_rows:
            feature_row = get_vec_feature(row)
            index = get_id_exist_cluster(feature_row)
            if index is None:
                index = add_new_cluster(feature_row)
            clusters[index].append(row)
        return clusters
        
       
     
   

extract_tree=ExtractTree()

In [7]:
def tree2fintoc_json(doc_tree) -> Dict:
    fintoc_json = []
    for id_node, node in doc_tree['nodes']['regions'].items():
        if node['label'] == 'header':
            reg = {
                "text":node['text'],
                "id": id_node,
                "page": node['metainfo']['page'] + 1, # В PageR специально оставил нумерацию с нуля (поскольку номер определяется не порядком, а пишится на странице и это еще не реализовано)
                "depth": node['header_level']
            }
            fintoc_json.append(reg)
    return fintoc_json

N = len(FILE_PATHS)
for i, file_path in enumerate(FILE_PATHS):    
    pdf_reader.read_from_file(file_path)
    pdf_reader.extract()
    pdf2tree.convert(pdf_reader, tree)
    extract_tree.extract(tree)
    
    doc_tree = tree.to_dict()
    pred_path = FINTOC_EN_PRED/(file_path.name+'.'+JSON_EXTENSION)
    # print(tree.document.md)
    
    rez = tree2fintoc_json(doc_tree)
    with open(pred_path, 'w') as f:
        json.dump(rez, f)

    print(f'{i+1}/{N} ({(i+1)/N*100:.2f}%)')

1/10 (10.00%)
2/10 (20.00%)
3/10 (30.00%)
4/10 (40.00%)

Cannot set gray non-stroke color because /'P0' is an invalid float value

5/10 (50.00%)
6/10 (60.00%)
7/10 (70.00%)
8/10 (80.00%)
9/10 (90.00%)
10/10 (100.00%)

In [8]:
import subprocess
import pandas as pd

In [9]:
subprocess.run(['python', 'metric.py', '--gt_folder', FINTOC_EN_ANNOTS, '--submission_folder', FINTOC_EN_PRED])
df = pd.read_csv('td_report.csv', delimiter='\t')
df[-2:-1][['Prec', 'Rec', 'F1']]

                   Prec                 Rec                  F1
49  0.46105189050171447  0.6057079550435704  0.4664353285809487

In [10]:
df = pd.read_csv('toc_report.csv', delimiter='\t')
tbl = df[-4:-3]
tbl[['Inex08-P', 'Inex08-R', 'Inex08-F1', 'Inex08-Title acc', 'Inex08-Level acc']]

   Inex08-P Inex08-R Inex08-F1 Inex08-Title acc Inex08-Level acc
55     30.2     31.4      28.0             45.3             33.7